# Generated by Django 4.1.9 on 2023-07-02 12:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("my_datetime_field", models.DateTimeField()),
            ],
            options={
                "db_table": "messagedb",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PersonaSession",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("age", models.CharField(max_length=100)),
                ("sex", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=100)),
                ("situation", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "personasession",
                "managed": False,
            },
        ),
    ]
