# Generated by Django 4.1.9 on 2023-07-02 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="%Y/%m/%d",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif"]
                            )
                        ],
                    ),
                ),
                ("body", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
